PANDAS

In [149]:
import pandas as pd
import numpy as np

In [5]:
Numeros = range(50,70,2)
print(list(Numeros))

[50, 52, 54, 56, 58, 60, 62, 64, 66, 68]


In [8]:
Numeros_series = pd.Series(Numeros)
print(Numeros_series)

0    50
1    52
2    54
3    56
4    58
5    60
6    62
7    64
8    66
9    68
dtype: int64


In [11]:
print(Numeros_series[2])

54


In [13]:
print(Numeros_series.index)

RangeIndex(start=0, stop=10, step=1)


In [15]:
print(Numeros_series.values)

[50 52 54 56 58 60 62 64 66 68]


In [19]:
Numeros_en_texto = ['primero','segunto','tercero','cuarto','quinto','sexto','septimo','octavo','noveno','decimo']
Numeros_series_2 = pd.Series(Numeros,index=Numeros_en_texto)
Numeros_series_2
print(Numeros_series_2)

primero    50
segunto    52
tercero    54
cuarto     56
quinto     58
sexto      60
septimo    62
octavo     64
noveno     66
decimo     68
dtype: int64


DataFrame

In [21]:
modelos = ['A1','A2','A3','A4','A5']
peso = [3500,3600,3800,3900,3200]
precios = [10000,11000,15000,12000,8000]


In [26]:
#Creo las series que necesito par armar mi dataframe

peso_series = pd.Series(peso,index=modelos)
precios_series = pd.Series(precios,index=modelos)

print(peso_series,"\n")
print(precios_series)

A1    3500
A2    3600
A3    3800
A4    3900
A5    3200
dtype: int64 

A1    10000
A2    11000
A3    15000
A4    12000
A5     8000
dtype: int64


In [28]:
#Construir el dataframe combinando las series
autos = pd.DataFrame({'Peso':peso_series, 'Precios':precios_series})
autos

Peso  Precios
A1  3500    10000
A2  3600    11000
A3  3800    15000
A4  3900    12000
A5  3200     8000

In [41]:
print(autos.head(2),'\n')
print(autos.shape)
print(autos.tail(2))
print(autos.describe(),'\n')
autos.info()
autos["Peso"]

    Peso  Precios
A1  3500    10000
A2  3600    11000 

(5, 2)
    Peso  Precios
A4  3900    12000
A5  3200     8000
              Peso       Precios
count     5.000000      5.000000
mean   3600.000000  11200.000000
std     273.861279   2588.435821
min    3200.000000   8000.000000
25%    3500.000000  10000.000000
50%    3600.000000  11000.000000
75%    3800.000000  12000.000000
max    3900.000000  15000.000000 

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A1 to A5
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Peso     5 non-null      int64
 1   Precios  5 non-null      int64
dtypes: int64(2)
memory usage: 292.0+ bytes


A1    3500
A2    3600
A3    3800
A4    3900
A5    3200
Name: Peso, dtype: int64

In [49]:
autos['Precio_por_Kg'] = (autos['Precios']/autos['Peso']).round(2)
print(autos['Precio_por_Kg'])
autos


A1    2.86
A2    3.06
A3    3.95
A4    3.08
A5    2.50
Name: Precio_por_Kg, dtype: float64


Peso  Precios  Precio_por_Kg
A1  3500    10000           2.86
A2  3600    11000           3.06
A3  3800    15000           3.95
A4  3900    12000           3.08
A5  3200     8000           2.50

In [51]:
autos.rename_axis('Modelos')

Peso  Precios  Precio_por_Kg
Modelos                              
A1       3500    10000           2.86
A2       3600    11000           3.06
A3       3800    15000           3.95
A4       3900    12000           3.08
A5       3200     8000           2.50

In [53]:
autos

Peso  Precios  Precio_por_Kg
A1  3500    10000           2.86
A2  3600    11000           3.06
A3  3800    15000           3.95
A4  3900    12000           3.08
A5  3200     8000           2.50

In [55]:
Numeros_series_2['quinto']

np.int64(58)

In [57]:
Numeros_series_2.loc['quinto']

np.int64(58)

In [60]:
Numeros_series_2.iloc[4]

np.int64(58)

In [68]:
autos_caros = autos.loc[autos['Precios'] > 10000, ['Precios', 'Precio_por_Kg']]
print(autos_caros)

    Precios  Precio_por_Kg
A2    11000           3.06
A3    15000           3.95
A4    12000           3.08


In [70]:
Numeros_3=range(51,70,2)
Numeros_en_texto = ['primero','segunto','tercero','cuarto','quinto','sexto','septimo','octavo','noveno','decimo']
Numeros_serie_3=pd.Series(Numeros_3,index=Numeros_en_texto)

In [72]:
print("serie Orignal")
print(Numeros_serie_3)

serie Orignal
primero    51
segunto    53
tercero    55
cuarto     57
quinto     59
sexto      61
septimo    63
octavo     65
noveno     67
decimo     69
dtype: int64


In [74]:
Numeros_cuadrados = Numeros_serie_3 **2
print("\n Serie con numeros al cuadrado:")
print(Numeros_cuadrados)


 Serie con numeros al cuadrado:
primero    2601
segunto    2809
tercero    3025
cuarto     3249
quinto     3481
sexto      3721
septimo    3969
octavo     4225
noveno     4489
decimo     4761
dtype: int64


In [84]:
# Definir las listas de datos
peso = [3583, 3627, 3561, 3880, 3814]
largo = [179, 179, 192, 192, 180]
modelos = ['A4 3.0 Quattro 4dr manual', 'A4 3.0 Quattro 4dr autos', 'A6 3.0 4dr', 'A6 3.0 Quattro 4dr', 'A4 3.0 convertible 2dr']

In [85]:
# Crear el DataFrame
Autos_2 = pd.DataFrame({'Peso': peso, 'Largo': largo}, index=modelos)

In [87]:
Porcentaje_autos = Autos_2 / Autos_2.iloc[0] *100

In [89]:
print("\nPorcentaje con Respecto a la Primera Fila:")
print(Porcentaje_autos)


Porcentaje con Respecto a la Primera Fila:
                                 Peso       Largo
A4 3.0 Quattro 4dr manual  100.000000  100.000000
A4 3.0 Quattro 4dr autos   101.228021  100.000000
A6 3.0 4dr                  99.385989  107.262570
A6 3.0 Quattro 4dr         108.289143  107.262570
A4 3.0 convertible 2dr     106.447111  100.558659


In [91]:
# Definir dos Series con índices diferentes
Numeros_en_texto_2 = ['primero', 'segundo', 'tercero', 'cuarto', 'quinto', 'sexto', 'séptimo', 'octavo', 'noveno', 'décimo'] 
Numeros_serie_2 = pd.Series([50, 52, 54, 56, 58, 60, 62, 64, 66, 68], index=Numeros_en_texto_2)

In [105]:
Numeros_en_texto_3 = ['segundo', 'cuarto', 'quinto', 'sexto', 'octavo', 'décimo', 'undécimo'] 
Numeros_serie_3 = pd.Series([100, 200, 300, 400, 500, 600, 700], index=Numeros_en_texto_3)

In [102]:
print("Numeros_serie_2:")
print(Numeros_serie_2)
print("\nNumeros_serie_3:")
print(Numeros_serie_3)

Numeros_serie_2:
primero    50
segundo    52
tercero    54
cuarto     56
quinto     58
sexto      60
séptimo    62
octavo     64
noveno     66
décimo     68
dtype: int64

Numeros_serie_3:
segundo     100
cuarto      200
quinto      300
sexto       400
octavo      500
decimo      600
undécimo    700
dtype: int64


In [106]:
Suma_Series = Numeros_serie_2 + Numeros_serie_3

In [108]:
# Mostrar el resultado de la suma
print("\nResultado de la Suma de las Series:") 
print(Suma_Series)


Resultado de la Suma de las Series:
cuarto      256.0
décimo      668.0
noveno        NaN
octavo      564.0
primero       NaN
quinto      358.0
segundo     152.0
sexto       460.0
séptimo       NaN
tercero       NaN
undécimo      NaN
dtype: float64


In [110]:
# Sumar las Series usando el método .add() 
Suma_Series_Add = Numeros_serie_2.add(Numeros_serie_3)

In [112]:
# Mostrar el resultado de la suma
print("Resultado de la Suma con .add():") 
print(Suma_Series_Add)

Resultado de la Suma con .add():
cuarto      256.0
décimo      668.0
noveno        NaN
octavo      564.0
primero       NaN
quinto      358.0
segundo     152.0
sexto       460.0
séptimo       NaN
tercero       NaN
undécimo      NaN
dtype: float64


In [114]:
# Sumar las Series usando el método .add() con fill_value
Suma_Series_Add_Fill = Numeros_serie_2.add(Numeros_serie_3, fill_value=0)
# Mostrar el resultado de la suma con fill_value
print("\nResultado de la Suma con .add() y fill_value:")
print(Suma_Series_Add_Fill)


Resultado de la Suma con .add() y fill_value:
cuarto      256.0
décimo      668.0
noveno       66.0
octavo      564.0
primero      50.0
quinto      358.0
segundo     152.0
sexto       460.0
séptimo      62.0
tercero      54.0
undécimo    700.0
dtype: float64


In [116]:
# Crear porciones de las Series
Numeros_serie_2_porcion = Numeros_serie_2[4:7]
Numeros_serie_3_porcion = Numeros_serie_3[5:8]
# Mostrar las porciones
print("Numeros_serie_2_porcion:")
print(Numeros_serie_2_porcion)
print("\nNumeros_serie_3_porcion:")
print(Numeros_serie_3_porcion)

# Sumar las porciones
Suma_Porciones = Numeros_serie_2_porcion + Numeros_serie_3_porcion
print("\nSuma de las porciones:")
print(Suma_Porciones)

Numeros_serie_2_porcion:
quinto     58
sexto      60
séptimo    62
dtype: int64

Numeros_serie_3_porcion:
décimo      600
undécimo    700
dtype: int64

Suma de las porciones:
décimo     NaN
quinto     NaN
sexto      NaN
séptimo    NaN
undécimo   NaN
dtype: float64


In [118]:
# Sumar las porciones con fill_value=0
Suma_Porciones = Numeros_serie_2_porcion.add(Numeros_serie_3_porcion, fill_value=0)
print(Suma_Porciones)

décimo      600.0
quinto       58.0
sexto        60.0
séptimo      62.0
undécimo    700.0
dtype: float64


In [120]:
# Crear una Serie con un valor NaN
serie = pd.Series([10, np.nan, 30])
# Sumar 5 a la Serie
resultado = serie + 5
print(resultado)

0    15.0
1     NaN
2    35.0
dtype: float64


In [122]:
#Comparar Nan con Nan
print(np.nan == np.nan)

False


In [124]:
#Detectar Nan en suna Serie
print(serie.isna())

0    False
1     True
2    False
dtype: bool


In [126]:
# Reemplazar NaN con un valor específico
serie_limpia = serie.fillna(0)
print(serie_limpia)

0    10.0
1     0.0
2    30.0
dtype: float64


In [128]:
# Crear un valor NaN
valor_nan = np.nan
# Operar con NaN
resultado = 2 * valor_nan
print(resultado)

nan


In [130]:
print(type(valor_nan))

<class 'float'>


In [135]:
# Calcula el producto de una lista con Nan
resultado = np.nanprod([2,valor_nan])
print(resultado)
print(type(resultado))

2.0


# Lectura de Archivos

#Leer archivo de csv

In [137]:
# Leer el archivo CSV
df = pd.read_csv('winequality-red.csv', sep=',')
# Mostrar las primeras filas del DataFrame con las columnas específicas
print(df[['density', 'pH', 'sulphates', 'alcohol', 'quality']].head())

   density    pH  sulphates  alcohol  quality
0   0.9978  3.51       0.56      9.4        5
1   0.9968  3.20       0.68      9.8        5
2   0.9970  3.26       0.65      9.8        5
3   0.9980  3.16       0.58      9.8        6
4   0.9978  3.51       0.56      9.4        5


In [157]:
import pandas as pd
import numpy as np
df = pd.read_excel('defaultoutput.xlsx')
# Mostrar las primeras filas del DataFrame con las columnas específicas
print(df[['index', 'ID', 'Year_Birth', 'Education', 'Income']].head())

   index    ID  Year_Birth   Education   Income
0      0  5524        1957  Graduation  58138.0
1      1  2174        1954  Graduation  46344.0
2      2  4141        1965  Graduation  71613.0
3      3  6182        1984  Graduation  26646.0
4      4  5324        1981         PhD  58293.0


In [160]:
import requests
# URL del archivo CSV
url = 'https://raw.githubusercontent.com/JJTorresDS/stocks-ds-edu/main/stocks.csv'
# Leer el archivo CSV desde la URL
df = pd.read_csv(url, index_col=0)
# Mostrar las primeras 5 filas de las columnas especificadas, redondeadas a 1 decimal
print(df[['AMZN', 'MCD', 'SBUX', 'GOOG', 'MSFT']].head(5).round(1))

                 AMZN    MCD  SBUX   GOOG  MSFT
formatted_date                                 
2016-01-01      587.0  106.3  54.4  743.0  49.9
2016-02-01      552.5  100.7  52.1  697.8  46.0
2016-03-01      593.6  108.8  53.6  745.0  50.3
2016-04-01      659.6  109.5  50.5  693.0  45.5
2016-05-01      722.8  105.6  49.3  735.7  48.3


In [162]:
import requests
# URL del archivo CSV
url = 'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/cars_clus.csv'
# Descargar el archivo CSV usando requests
response = requests.get(url)
# Verificar que la solicitud fue exitosa
if response.status_code == 200:
    # Guardar el contenido en un archivo local
    with open('cars_clus.csv', 'wb') as file:
        file.write(response.content)
    
    # Leer el archivo CSV usando pandas
    pdf = pd.read_csv('cars_clus.csv')
    # Imprimir la forma del DataFrame y las primeras 5 filas
    print("Shape: ", pdf.shape)
    print(pdf.head(5))
else:
    print("Error al descargar el archivo. Código de estado:", response.status_code)

Shape:  (159, 16)
  manufact    model   sales  resale   type   price engine_s horsepow wheelbas  \
0    Acura  Integra  16.919  16.360  0.000  21.500    1.800  140.000  101.200   
1    Acura       TL  39.384  19.875  0.000  28.400    3.200  225.000  108.100   
2    Acura       CL  14.114  18.225  0.000  $null$    3.200  225.000  106.900   
3    Acura       RL   8.588  29.725  0.000  42.000    3.500  210.000  114.600   
4     Audi       A4  20.397  22.255  0.000  23.990    1.800  150.000  102.600   

    width   length curb_wgt fuel_cap     mpg lnsales  partition  
0  67.300  172.400    2.639   13.200  28.000   2.828        0.0  
1  70.300  192.900    3.517   17.200  25.000   3.673        0.0  
2  70.600  192.000    3.470   17.200  26.000   2.647        0.0  
3  71.400  196.600    3.850   18.000  22.000   2.150        0.0  
4  68.200  178.000    2.998   16.400  27.000   3.015        0.0  


# Arrays

In [165]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d,'\n')
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d,'\n')
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d,'\n')

[1 2 3 4 5] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 



# Creación de ndarrays

In [170]:
# Crear un ndarray usando np.array() con un rango de números
Npa = np.array(range(10))
# Mostrar el array
print(Npa)
Np_cero = np.zeros(10)
Np_cero



[0 1 2 3 4 5 6 7 8 9]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [171]:
Np_relleno = np.full(10,256)
Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [175]:
Np_uno = np.ones(10)
Np_uno
print(Np_uno)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [176]:
Np_cero_int = np.zeros(10, dtype=int)
Np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [178]:
Np_rango = np.arange(10)
print(Np_rango)

[0 1 2 3 4 5 6 7 8 9]


In [185]:
Np_random_dimensiones = np.random.randint(10, size=(3, 4))
print(Np_random_dimensiones)

# Crear un array de números de punto flotante
arr = np.array([1.1, 2.1, 3.1])

# Convertir el tipo de dato del array a entero
newarr = arr.astype('i') # Imprimir el nuevo array y su tipo de dato print(newarr) print(newarr.dtype)

[[2 5 1 3]
 [3 4 8 9]
 [5 3 7 7]]


In [186]:
# Crear un array de dos dimensiones con valores enteros aleatorios
Np_random_dimensiones = np.random.randint(10, size=(3, 4))
# Imprimir el array
print(Np_random_dimensiones)
# Ver la forma del array
print("Forma de Np_random_dimensiones:", Np_random_dimensiones.shape)
# Ver el tamaño del array
print("Tamaño de Np_random_dimensiones:", Np_random_dimensiones.size)
# Crear arrays con diferentes tipos de datos
Np_cero = np.zeros(10)
Np_cero_int = np.zeros(10, dtype=int)

# Ver el tipo de dato
print("Tipo de dato de Np_cero:", Np_cero.dtype)
print("Tipo de dato de Np_cero_int:", Np_cero_int.dtype)
# Ver el tamaño del elemento en bytes
print("Tamaño de cada elemento en Np_random_dimensiones:", Np_random_dimensiones.itemsize)

[[2 9 4 5]
 [0 0 8 9]
 [2 0 2 2]]
Forma de Np_random_dimensiones: (3, 4)
Tamaño de Np_random_dimensiones: 12
Tipo de dato de Np_cero: float64
Tipo de dato de Np_cero_int: int64
Tamaño de cada elemento en Np_random_dimensiones: 4


In [188]:
# Crear un arreglo con números del 1 al 64
numeros = np.arange(1, 65)
# Cambiar la forma del arreglo a una grilla de 8x8
grilla = numeros.reshape(8, 8)
# Mostrar el resultado
print(grilla)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [190]:
# Crear un arreglo concatenado
Arrays_concatenados = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Dividir en dos partes usando un punto de corte
Array_partido = np.split(Arrays_concatenados, [2])

print("Array_concatenados:", Arrays_concatenados)
print("Array_partido:", Array_partido)

# Crear un arreglo concatenado
Arrays_concatenados = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Dividir en tres partes usando dos puntos de corte
Array_partido_2 = np.split(Arrays_concatenados, [2, 8])

# Asignar a variables distintas
Parte_1, Parte_2, Parte_3 = Array_partido_2

print("Parte_1:", Parte_1)
print("Parte_2:", Parte_2)
print("Parte_3:", Parte_3)

Array_concatenados: [ 1  2  3  4  5  6  7  8  9 10]
Array_partido: [array([1, 2]), array([ 3,  4,  5,  6,  7,  8,  9, 10])]
Parte_1: [1 2]
Parte_2: [3 4 5 6 7 8]
Parte_3: [ 9 10]
